import { MainLayout } from "@/layouts";
import { Montserrat } from 'next/font/google'
import { type LayoutWithChildren } from "@/types";
import AuthLayout from "@/providers";
import '../globals.css';

// const montserrat = Montserrat({ subsets: ["latin", "cyrillic"], variable: "--font-montserrat" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: LayoutWithChildren) {
  return (
    <html lang="en">
      <body>
        <AuthLayout>
          <MainLayout>
            {children}
          </MainLayout>
        </AuthLayout>
      </body>
    </html>
  )
}

